Console.Write("Введите число: ");
int x1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите число: ");
int x2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите число: ");
int y1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите число: ");
int y2 = Convert.ToInt32(Console.ReadLine());
double result = Math.Sqrt(Math.Pow(x2-x1,2)+Math.Pow(y2-y1,2));
Console.WriteLine(Math.Round(result,3));